/*
 * Adminsucelje.java
 *
 * Created on 2007. svibanj 21, 20:26
 */

/**
 *
 * @author  DGaso
 */
 import java.sql.ResultSet; 
 import java.sql.SQLException;
 import javax.swing.JOptionPane;
 
 
 
 
public class Adminsucelje extends javax.swing.JFrame {
 
  
    /** Creates new form Adminsucelje */
    public Adminsucelje() {
        initComponents();
        this.setTitle("ADMINISTRATORSKO SUCELJE");
        popuniZupanije();
        popuniGradove();
       
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textime = new javax.swing.JTextField();
        textprezime = new javax.swing.JTextField();
        textadresa = new javax.swing.JTextField();
        texttelefon = new javax.swing.JTextField();
        textmobitel = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        combozupanija = new javax.swing.JComboBox();
        combograd = new javax.swing.JComboBox();
        textstatus = new javax.swing.JTextField();
        odustani = new javax.swing.JButton();
        spremi = new javax.swing.JButton();
        ulazudjelsuc = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textuzer = new javax.swing.JTextField();
        textpass = new javax.swing.JTextField();
        comboposlovnica = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 102));
        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("IME :");

        jLabel2.setText("PREZIME :");

        jLabel3.setText("ADRESA :");

        jLabel4.setText("TELEFON :");

        jLabel5.setText("MOBITEL :");

        jLabel6.setText("EMAIL :");

        jLabel7.setText("GRAD :");

        jLabel8.setText("\u017dUPANIJA :");

        jLabel10.setText("STATUS :");

        jLabel13.setText("POSLOVNICA :");

        combozupanija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combozupanijaActionPerformed(evt);
            }
        });

        combograd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogradActionPerformed(evt);
            }
        });

        odustani.setFont(new java.awt.Font("Arial Unicode MS", 3, 10));
        odustani.setText("RESET UNOSA");
        odustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odustaniActionPerformed(evt);
            }
        });

        spremi.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        spremi.setIcon(new javax.swing.ImageIcon("E:\\netbeans\\AutoKuca\\import2.png"));
        spremi.setText("SPREMI");
        spremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spremiActionPerformed(evt);
            }
        });

        ulazudjelsuc.setBackground(new java.awt.Color(255, 0, 0));
        ulazudjelsuc.setFont(new java.awt.Font("Arial Unicode MS", 2, 11));
        ulazudjelsuc.setIcon(new javax.swing.ImageIcon("E:\\netbeans\\AutoKuca\\signpost.png"));
        ulazudjelsuc.setText("ulaz u djelatnicko sucelje");
        ulazudjelsuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulazudjelsucActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("uzer :");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("pass :");

        comboposlovnica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "centar" }));
        comboposlovnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboposlovnicaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel1)
                                    .add(jLabel3))
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(textime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(textprezime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(combozupanija, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(textadresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(15, 15, 15)
                                .add(odustani)
                                .add(31, 31, 31)
                                .add(spremi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel13)
                                .add(14, 14, 14)
                                .add(comboposlovnica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel6)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel7)
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                .add(jLabel11)
                                                .add(jLabel10)
                                                .add(jLabel12))))
                                    .add(jLabel4))
                                .add(15, 15, 15)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(texttelefon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(combograd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(textmobitel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, textemail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, textpass)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, textuzer)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, textstatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                            .add(ulazudjelsuc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(textime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(texttelefon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(textprezime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(textmobitel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(textadresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(textemail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(60, 60, 60)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(combozupanija, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(combograd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(52, 52, 52)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(textstatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(comboposlovnica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(textuzer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11))))
                .add(2, 2, 2)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(textpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(odustani, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(spremi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ulazudjelsuc)))
                .addContainerGap())
        );
        jTabbedPane1.addTab("unos djelatnika", jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 615, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odustaniActionPerformed
         reset();
    }//GEN-LAST:event_odustaniActionPerformed

    private void comboposlovnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboposlovnicaActionPerformed
         popuniPoslovnice();
    }//GEN-LAST:event_comboposlovnicaActionPerformed

    private void ulazudjelsucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulazudjelsucActionPerformed
            Radnosucelje rs= new Radnosucelje();
            rs.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_ulazudjelsucActionPerformed

    private void spremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spremiActionPerformed
        Djelatnik d= new  Djelatnik();
        
        d.setIme(textime.getText());
        d.setPrezime(textprezime.getText());
        d.setAdresa(textadresa.getText());
        d.setTelefon(texttelefon.getText());
        d.setMobitel(textmobitel.getText());
        d.setEmail(textemail.getText());
        d.setGrad(combograd.getSelectedItem().toString());
        d.setZupanija(combozupanija.getSelectedItem().toString());
        d.setPoslovnica(comboposlovnica.getSelectedItem().toString());
        d.setStatus(textstatus.getText());
        d.setUzer(textuzer.getText());
        d.setPass(textpass.getText());
        
        JOptionPane opt=new JOptionPane();
        
        if(d.valjaniPodaci()){
            boolean uspjesno=Metode.spremiDjelatnika(d);
            
            if(uspjesno){
                
                opt.showMessageDialog(this,"Uspješno snimljeno","OBAVIJEST",JOptionPane.INFORMATION_MESSAGE);
                reset();
                Metode.dajSveDjelatnike();
            }else{
                opt.showMessageDialog(this,"Nije snimljeno","POZOR",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            opt.showMessageDialog(this,"Molim upišite ime i prezime","POZOR",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_spremiActionPerformed

    private void combozupanijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combozupanijaActionPerformed
        
        popuniGradove();
    }//GEN-LAST:event_combozupanijaActionPerformed

    private void popuniZupanije(){
        combozupanija.removeAllItems();
        ResultSet zupanija=Metode.DajZupanije();
        try {
            while(zupanija.next()){
                combozupanija.addItem(zupanija.getString("nazivzupanije"));
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } 
     private void popuniPoslovnice(){
        comboposlovnica.removeAllItems();
        ResultSet poslovnica=Metode.dajSvePoslovnice();
        try {
            while(poslovnica.next()){
                comboposlovnica.addItem(poslovnica.getString("nazivposlovnice"));
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } 
    
    

     
    
    
    private void combogradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogradActionPerformed
    
    }//GEN-LAST:event_combogradActionPerformed
    private void popuniGradove(){
        combograd.removeAllItems();
        String zupanija=combozupanija.getSelectedItem().toString();
        
        ResultSet grad=Metode.DajGradoveOdZupanija(zupanija);
        try {
            while(grad.next()){
                 combograd.addItem(grad.getString("nazivgrada"));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
     
        
    }
    public void reset(){
       textime.setText("");
       textprezime.setText("");
       textadresa.setText("");
       texttelefon.setText("");
       textmobitel.setText("");
       textemail.setText("");
       textstatus.setText("");
       textuzer.setText("");
       textpass.setText("");
       
       comboposlovnica.setSelectedItem(0);
       combograd.setSelectedItem(0);
       combozupanija.setSelectedItem(0);
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminsucelje().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combograd;
    private javax.swing.JComboBox comboposlovnica;
    private javax.swing.JComboBox combozupanija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton odustani;
    private javax.swing.JButton spremi;
    private javax.swing.JTextField textadresa;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textime;
    private javax.swing.JTextField textmobitel;
    private javax.swing.JTextField textpass;
    private javax.swing.JTextField textprezime;
    private javax.swing.JTextField textstatus;
    private javax.swing.JTextField texttelefon;
    private javax.swing.JTextField textuzer;
    private javax.swing.JButton ulazudjelsuc;
    // End of variables declaration//GEN-END:variables
    
}
