import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.io.File;

/**
 *
 * @author  soga
 */
public class Kartica extends javax.swing.JFrame {
    
    String sql;
    ResultSet rs;
    File f;
    ImageLabel slikica;
        
    
    /** Creates new form Kartica */
    
    public Kartica(int id) {
        initComponents();
      
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       this.setTitle("Kartica vozila");
        slikica=new ImageLabel();
        slikica.setBounds(100,200,200,200);
        slikica.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.add(slikica);
        
        sql="select * from auto where id="+id;
        rs=Metode.dajAutePoSqlUpitu(sql);
        try {
            rs.next();
            lblmarka.setText(rs.getString("markavozila"));
            lbltip.setText(rs.getString("tipvozila"));
            lblsnaga.setText(rs.getString("snagaukilovatima"));
            lblkm.setText(rs.getString("prijedjenikilometri"));
            lblvrsta.setText(rs.getString("vrstavozila"));
            lblvrstagoriva.setText(rs.getString("vrstagoriva"));
            lblvrstamotora.setText(rs.getString("vrstagoriva"));
            slikica.prikaziSliku(rs.getString("slika"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
       
       

        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        lblvrstagoriva = new javax.swing.JLabel();
        labvrstamotora = new javax.swing.JLabel();
        lblkm = new javax.swing.JLabel();
        labvrstagoriva = new javax.swing.JLabel();
        labsnaga = new javax.swing.JLabel();
        lblmarka = new javax.swing.JLabel();
        lblsnaga = new javax.swing.JLabel();
        lblvrsta = new javax.swing.JLabel();
        lbltip = new javax.swing.JLabel();
        labprijedjenikm = new javax.swing.JLabel();
        lblvrstamotora = new javax.swing.JLabel();
        labvrsta = new javax.swing.JLabel();
        labmarka = new javax.swing.JLabel();
        labtip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lblvrstagoriva.setText("jLabel10");

        labvrstamotora.setText("vrsta motora");

        lblkm.setText("jLabel9");

        labvrstagoriva.setText("vrsta goriva");

        labsnaga.setText("snaga(kW)");

        lblmarka.setText("jLabel1");

        lblsnaga.setText("jLabel7");

        lblvrsta.setText("jLabel3");

        lbltip.setText("jLabel2");

        labprijedjenikm.setText("prijedjeni km");

        lblvrstamotora.setText("jLabel6");

        labvrsta.setText("vrsta");

        labmarka.setText("marka");

        labtip.setText("tip");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labvrsta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblvrsta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 155, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labtip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labmarka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblmarka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbltip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(labvrstamotora, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .add(labprijedjenikm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labsnaga, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(labvrstagoriva, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(39, 39, 39)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblkm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblvrstamotora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblsnaga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblvrstagoriva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labmarka)
                    .add(lblmarka)
                    .add(lblvrstamotora)
                    .add(labvrstamotora))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labvrsta)
                    .add(lblvrsta)
                    .add(lblkm)
                    .add(labprijedjenikm))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labtip)
                    .add(lbltip)
                    .add(lblsnaga)
                    .add(labsnaga))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblvrstagoriva)
                    .add(labvrstagoriva))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labmarka;
    private javax.swing.JLabel labprijedjenikm;
    private javax.swing.JLabel labsnaga;
    private javax.swing.JLabel labtip;
    private javax.swing.JLabel labvrsta;
    private javax.swing.JLabel labvrstagoriva;
    private javax.swing.JLabel labvrstamotora;
    private javax.swing.JLabel lblkm;
    private javax.swing.JLabel lblmarka;
    private javax.swing.JLabel lblsnaga;
    private javax.swing.JLabel lbltip;
    private javax.swing.JLabel lblvrsta;
    private javax.swing.JLabel lblvrstagoriva;
    private javax.swing.JLabel lblvrstamotora;
    // End of variables declaration//GEN-END:variables
    
}
