import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.*;
import java.util.Vector;
/*
 * Radnosucelje.java
 *
 * Created on 2007. svibanj 19, 16:40
 */

/**
 *
 * @author  soga
 */
public class Radnosucelje extends javax.swing.JFrame {
    
    RSTableModel tableModel= new RSTableModel();
    Vector<Auto> v=Metode.dajSveAute();
    int trenutnaPozicija=0;
    
  
    File f;
   
    ImageLabel slika;
    ImageLabel slika2;
    
    
    /** Creates new form Radnosucelje */
    public Radnosucelje() {
        initComponents();
        slika=new ImageLabel();
        slika.setBounds(350,300,200,200);
        slika.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jpanunosautomobila.add(slika);
        slika2=new ImageLabel();
        slika2.setBounds(430,200,200,200);
        slika2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jpanponudaautomobila.add(slika2);
        this.setTitle("RADNO SUCELJE");
        prikaziAuto();
        
        tablicapretrazivaca.setModel(tableModel);
        popuniCmbKriterij(); 
        
        
        
        
        
        
        
    }
    private void popuniCmbKriterij(){
          cmbkriterij.addItem("markavozila");
          cmbkriterij.addItem("tipvozila");
          cmbkriterij.addItem("vrstavozila");
    }
          
     private void prikaziKarticu(int id) {
        new Kartica(id).setVisible(true);
        
    } 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanponudaautomobila = new javax.swing.JPanel();
        patxtmarka = new javax.swing.JTextField();
        patxttip = new javax.swing.JTextField();
        patxtvrsta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patxtboja = new javax.swing.JTextField();
        patxtgodinapr = new javax.swing.JTextField();
        patxtvrstamotora = new javax.swing.JTextField();
        patxtsnaga = new javax.swing.JTextField();
        patxtzapremina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        patxtprijedkil = new javax.swing.JTextField();
        patxtcijena = new javax.swing.JTextField();
        patxtstatus = new javax.swing.JTextField();
        patxtvrstagoriva = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbutlistajnazad = new javax.swing.JButton();
        jbutlistajnapred = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        patadodatnaoprema = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jpanpretrazivac = new javax.swing.JPanel();
        txtupit = new javax.swing.JTextField();
        cmbkriterij = new javax.swing.JComboBox();
        dugmePretrazi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablicapretrazivaca = new javax.swing.JTable();
        jpanunosautomobila = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textmarka = new javax.swing.JTextField();
        texttip = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAdodatnaop = new javax.swing.JTextArea();
        textboja = new javax.swing.JTextField();
        textpredjkilom = new javax.swing.JTextField();
        textgodinaproizvodnje = new javax.swing.JTextField();
        textvrstamotora = new javax.swing.JTextField();
        textsnagakW = new javax.swing.JTextField();
        textzapreminaccm = new javax.swing.JTextField();
        textvrstagoriva = new javax.swing.JTextField();
        textstatus = new javax.swing.JTextField();
        textcijena = new javax.swing.JTextField();
        textvrsta = new javax.swing.JTextField();
        jbutSLIKE = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        butonsnimi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
        });

        jpanponudaautomobila.setBackground(new java.awt.Color(255, 255, 255));
        jpanponudaautomobila.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanponudaautomobila.setLayout(null);
        jpanponudaautomobila.add(patxtmarka);
        patxtmarka.setBounds(120, 40, 160, 20);
        jpanponudaautomobila.add(patxttip);
        patxttip.setBounds(120, 70, 160, 20);
        jpanponudaautomobila.add(patxtvrsta);
        patxtvrsta.setBounds(120, 100, 160, 20);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel1.setText("marka:");
        jpanponudaautomobila.add(jLabel1);
        jLabel1.setBounds(50, 40, 39, 15);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel2.setText("tip:");
        jpanponudaautomobila.add(jLabel2);
        jLabel2.setBounds(70, 70, 18, 15);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel3.setText("vrsta:");
        jpanponudaautomobila.add(jLabel3);
        jLabel3.setBounds(50, 100, 34, 15);
        jpanponudaautomobila.add(patxtboja);
        patxtboja.setBounds(200, 200, 80, 20);
        jpanponudaautomobila.add(patxtgodinapr);
        patxtgodinapr.setBounds(200, 130, 80, 20);
        jpanponudaautomobila.add(patxtvrstamotora);
        patxtvrstamotora.setBounds(200, 280, 80, 20);
        jpanponudaautomobila.add(patxtsnaga);
        patxtsnaga.setBounds(200, 350, 80, 20);
        jpanponudaautomobila.add(patxtzapremina);
        patxtzapremina.setBounds(200, 320, 80, 20);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel4.setText("boja:");
        jpanponudaautomobila.add(jLabel4);
        jLabel4.setBounds(90, 200, 28, 15);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel5.setText("godina proizvodnje :");
        jpanponudaautomobila.add(jLabel5);
        jLabel5.setBounds(10, 130, 120, 15);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel6.setText("vrsta motora:");
        jpanponudaautomobila.add(jLabel6);
        jLabel6.setBounds(30, 280, 80, 20);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel7.setText("snaga(kW):");
        jpanponudaautomobila.add(jLabel7);
        jLabel7.setBounds(80, 350, 67, 15);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel8.setText("zapremina motora(ccm) :");
        jpanponudaautomobila.add(jLabel8);
        jLabel8.setBounds(10, 320, 143, 15);
        jpanponudaautomobila.add(patxtprijedkil);
        patxtprijedkil.setBounds(200, 160, 80, 20);
        jpanponudaautomobila.add(patxtcijena);
        patxtcijena.setBounds(600, 140, 70, 20);
        jpanponudaautomobila.add(patxtstatus);
        patxtstatus.setBounds(400, 140, 60, 20);
        jpanponudaautomobila.add(patxtvrstagoriva);
        patxtvrstagoriva.setBounds(200, 240, 80, 20);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel9.setText("prijedjeni kilometri:");
        jpanponudaautomobila.add(jLabel9);
        jLabel9.setBounds(10, 160, 108, 15);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel10.setText("vrsta goriva:");
        jpanponudaautomobila.add(jLabel10);
        jLabel10.setBounds(40, 240, 74, 15);

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel11.setText("status:");
        jpanponudaautomobila.add(jLabel11);
        jLabel11.setBounds(350, 140, 40, 15);

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("cijena :");
        jpanponudaautomobila.add(jLabel12);
        jLabel12.setBounds(540, 140, 42, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("dodatna oprema:");
        jpanponudaautomobila.add(jLabel13);
        jLabel13.setBounds(300, 40, 83, 14);

        jbutlistajnazad.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jbutlistajnazad.setText("listaj nazad");
        jbutlistajnazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutlistajnazadActionPerformed(evt);
            }
        });
        jpanponudaautomobila.add(jbutlistajnazad);
        jbutlistajnazad.setBounds(339, 430, 140, 60);

        jbutlistajnapred.setFont(new java.awt.Font("Arial Unicode MS", 3, 11)); // NOI18N
        jbutlistajnapred.setText("listaj naprijed");
        jbutlistajnapred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutlistajnapredActionPerformed(evt);
            }
        });
        jpanponudaautomobila.add(jbutlistajnapred);
        jbutlistajnapred.setBounds(540, 430, 150, 60);

        patadodatnaoprema.setColumns(20);
        patadodatnaoprema.setRows(5);
        jScrollPane2.setViewportView(patadodatnaoprema);

        jpanponudaautomobila.add(jScrollPane2);
        jScrollPane2.setBounds(400, 40, 270, 96);

        jButton1.setText("izmjeni podatak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpanponudaautomobila.add(jButton1);
        jButton1.setBounds(67, 450, 180, 23);

        jTabbedPane1.addTab("PONUDA AUTOMOBILA", jpanponudaautomobila);

        txtupit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtupitKeyPressed(evt);
            }
        });

        dugmePretrazi.setText("PRETRAŽI");
        dugmePretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmePretraziActionPerformed(evt);
            }
        });
        dugmePretrazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dugmePretraziKeyPressed(evt);
            }
        });

        tablicapretrazivaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablicapretrazivaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablicapretrazivacaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablicapretrazivaca);

        org.jdesktop.layout.GroupLayout jpanpretrazivacLayout = new org.jdesktop.layout.GroupLayout(jpanpretrazivac);
        jpanpretrazivac.setLayout(jpanpretrazivacLayout);
        jpanpretrazivacLayout.setHorizontalGroup(
            jpanpretrazivacLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpanpretrazivacLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .add(jpanpretrazivacLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtupit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbkriterij, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(424, 424, 424))
            .add(jpanpretrazivacLayout.createSequentialGroup()
                .add(jpanpretrazivacLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpanpretrazivacLayout.createSequentialGroup()
                        .add(276, 276, 276)
                        .add(dugmePretrazi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jpanpretrazivacLayout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 610, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanpretrazivacLayout.setVerticalGroup(
            jpanpretrazivacLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpanpretrazivacLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(txtupit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(31, 31, 31)
                .add(cmbkriterij, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22)
                .add(dugmePretrazi)
                .add(15, 15, 15)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51))
        );

        jTabbedPane1.addTab("pretraživač", jpanpretrazivac);

        jpanunosautomobila.setBackground(new java.awt.Color(255, 255, 204));
        jpanunosautomobila.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jpanunosautomobilaComponentHidden(evt);
            }
        });

        jLabel14.setText("marka vozila:");

        jLabel15.setText("tip vozila:");

        jLabel16.setText("vrsta vozila:");

        jLabel17.setText("boja:");

        jLabel18.setText("godina proizvodnje:");

        jLabel19.setText("vrsta motora:");

        jLabel20.setText("snaga(kW):");

        jLabel21.setText("zapremina(ccm):");

        jLabel22.setText("prijedjeni kilometri:");

        jLabel23.setText("vrsta goriva:");

        jLabel24.setText("status:");

        jLabel25.setText("cijena:");

        jLabel26.setText("dodatna oprema:");

        textAdodatnaop.setColumns(20);
        textAdodatnaop.setRows(5);
        jScrollPane1.setViewportView(textAdodatnaop);

        textvrstagoriva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textvrstagorivaActionPerformed(evt);
            }
        });

        jbutSLIKE.setText("SLIKE");
        jbutSLIKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutSLIKEActionPerformed(evt);
            }
        });

        jLabel27.setText("odaberi direktorij za spremanje slika vozila:");

        butonsnimi.setText("SNIMI");
        butonsnimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonsnimiActionPerformed(evt);
            }
        });

        jButton2.setText("PONOVI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpanunosautomobilaLayout = new org.jdesktop.layout.GroupLayout(jpanunosautomobila);
        jpanunosautomobila.setLayout(jpanunosautomobilaLayout);
        jpanunosautomobilaLayout.setHorizontalGroup(
            jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpanunosautomobilaLayout.createSequentialGroup()
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(jLabel23)
                                .add(34, 34, 34)
                                .add(textvrstagoriva))
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel21)
                                    .add(jLabel20)
                                    .add(jLabel17)
                                    .add(jLabel14)
                                    .add(jLabel15)
                                    .add(jLabel16)
                                    .add(jLabel18))
                                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                                        .add(32, 32, 32)
                                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(textgodinaproizvodnje)
                                            .add(texttip)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textzapreminaccm)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textsnagakW)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textvrsta)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textpredjkilom)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textboja, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textvrstamotora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                                        .add(44, 44, 44)
                                        .add(textmarka))))
                            .add(jLabel22)
                            .add(jLabel19)))
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton2)))
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jLabel26))
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(95, 95, 95)
                                .add(jLabel24)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel27)
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(47, 47, 47)
                                .add(jLabel25)
                                .add(40, 40, 40)
                                .add(textcijena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(textstatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 273, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .add(321, 321, 321)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jbutSLIKE)
                            .add(butonsnimi))))
                .add(242, 242, 242))
        );
        jpanunosautomobilaLayout.setVerticalGroup(
            jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpanunosautomobilaLayout.createSequentialGroup()
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel14)
                            .add(textmarka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel15)
                            .add(texttip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(22, 22, 22)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel16)
                            .add(textvrsta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel18)
                            .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(textgodinaproizvodnje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel24))))
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(39, 39, 39)
                                .add(jLabel26))
                            .add(jpanunosautomobilaLayout.createSequentialGroup()
                                .add(23, 23, 23)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(42, 42, 42)
                        .add(textstatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(25, 25, 25)
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(jLabel25)
                    .add(textcijena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textvrstamotora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(textpredjkilom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpanunosautomobilaLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel17)
                            .add(textboja, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel20)
                            .add(textsnagakW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel21)
                            .add(textzapreminaccm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(19, 19, 19)
                        .add(jpanunosautomobilaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel23)
                            .add(textvrstagoriva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(15, 15, 15)
                        .add(jButton2))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jpanunosautomobilaLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jbutSLIKE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 84, Short.MAX_VALUE)
                        .add(butonsnimi)
                        .add(45, 45, 45)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("unos automobila", jpanunosautomobila);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 735, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//       if(txtIme.getText().length() < 3 | txtPrezime.getText().length() < 3 | txtAdresa.getText().length() < 5 | txtPassword.getText().length() < 5){
//         jop.showMessageDialog(this,"Zaposlenik mora imati min 3 slova za ime,prezime,adresu i 5 za password");
//         return;
//        }
        JOptionPane jop= new JOptionPane();
        
        int odluka = jop.showConfirmDialog(this,"Dali zelite doista modificirati podatke o ovom autu ?","Obavjest",JOptionPane.YES_NO_OPTION) ;
    
        switch(odluka){
            
            case JOptionPane.YES_OPTION:
               
                Auto a=v.elementAt(trenutnaPozicija);
                
                 System.out.println("Prikaz id-a :"+trenutnaPozicija);
                
                
                a.setBoja(patxtboja.getText());
                a.setCijenaVozila(patxtcijena.getText());
                a.setDodatnaOprema(patadodatnaoprema.getText());
                a.setGodinaProizvodnje(patxtgodinapr.getText());
                a.setMarkaVozila(patxtmarka.getText());
                a.setPrijedjeniKilometri(patxtprijedkil.getText());
                a.setSnagaUKilovatima(patxtsnaga.getText());
                a.setStatus(patxtstatus.getText());
                a.setTipVozila(patxttip.getText());
                a.setVrstaGoriva(patxtvrstagoriva.getText());
                a.setVrstaMotora(patxtvrstamotora.getText());
                a.setVrstaVozila(patxtvrsta.getText());
                a.setZapreminaMotora(patxtzapremina.getText());
              
                //izmjena slike
                
                
//                String sl="";
//                 for(int i=0;i<f.getAbsolutePath().length();i++){
//                   if(f.getAbsolutePath().charAt(i)=='\\'){
//                   sl=sl+"\\";
//                   }
//                sl=sl+f.getAbsolutePath().charAt(i);
//            
//                  }
//                a.setSlika(sl);
                
                boolean rezultat = Metode.modificirajAuto(a);
                System.out.println("jel ovo dobar id?"+a.getId());
                 System.out.println("jel ovo dobra promjena?"+a.getVrstaVozila());
                if(rezultat) {
                    jop.showMessageDialog(this,"Auto je modificiran","Obavjest",JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    v = Metode.dajSveAute();
                  System.out.println("a jel sad  dobar id?"+a.getId());
                   System.out.println("a jel sad dobra promjena?"+a.getVrstaVozila());
                    break;
                }
                else jop.showMessageDialog(this,"Auto nije modificiran","Obavjest",JOptionPane.INFORMATION_MESSAGE);
                break;
                
            case JOptionPane.NO_OPTION:
               
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablicapretrazivacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablicapretrazivacaMouseClicked
     if(evt.getClickCount()==2){
            System.out.print(tableModel.getValueAt(tablicapretrazivaca.getSelectedRow(),0)+" - ");
             System.out.print(tableModel.getValueAt(tablicapretrazivaca.getSelectedRow(),1)+" - ");
             System.out.print(tableModel.getValueAt(tablicapretrazivaca.getSelectedRow(),2)+"\n");
      
       int id=Integer.parseInt(tableModel.getValueAt(tablicapretrazivaca.getSelectedRow(),0).toString());
       prikaziKarticu(id);
        }
      
    }//GEN-LAST:event_tablicapretrazivacaMouseClicked

    private void dugmePretraziKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dugmePretraziKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             dugmePretraziActionPerformed(null);
         }
    }//GEN-LAST:event_dugmePretraziKeyPressed

    private void dugmePretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmePretraziActionPerformed
        System.out.println("dugme pretrazi");
         String upit="select id,markavozila,tipvozila,vrstavozila  from auto where lower("+cmbkriterij.getSelectedItem().toString()+") like lower('"+txtupit.getText()+"%'); ";
          System.out.println("citanje upita  proslo");
         ResultSet rs= Metode.dajAutePoSqlUpitu(upit);
          System.out.println("poziv metode dajpoupitu");
         tableModel.setResultSet(rs);
           
    }//GEN-LAST:event_dugmePretraziActionPerformed

    private void txtupitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtupitKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            dugmePretraziActionPerformed(null);
      }
    }//GEN-LAST:event_txtupitKeyPressed

    private void textvrstagorivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textvrstagorivaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_textvrstagorivaActionPerformed

    private void jbutlistajnazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutlistajnazadActionPerformed
       System.out.println("nazad.trenutnaPozicija=" + trenutnaPozicija);
        trenutnaPozicija--;
        
        if(trenutnaPozicija<0) {
            trenutnaPozicija = v.size() - 1;
            if(trenutnaPozicija<0) {
                trenutnaPozicija =0;
            }
        }
        prikaziAuto();
        System.out.println("nazad.trenutnaPozicija=" + trenutnaPozicija);
       
    }//GEN-LAST:event_jbutlistajnazadActionPerformed

    private void jbutlistajnapredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutlistajnapredActionPerformed
        System.out.println("napred.trenutnaPozicija=" + trenutnaPozicija);
        trenutnaPozicija++;
        if(trenutnaPozicija > v.size()-1){ 
            trenutnaPozicija =0;    
        }
        prikaziAuto();
        System.out.println("napred.trenutnaPozicija=" + trenutnaPozicija);
    }//GEN-LAST:event_jbutlistajnapredActionPerformed

    private void jbutSLIKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutSLIKEActionPerformed
       JFileChooser fc=new JFileChooser(".");
        int result=fc.showOpenDialog(this);
        switch(result){
            case JFileChooser.CANCEL_OPTION:
                //labela.setText("ni�ta niste odabrali");
                break;
            case JFileChooser.APPROVE_OPTION:
                f=fc.getSelectedFile();
                if(f!=null){
                    slika.prikaziSliku(f.getAbsolutePath());
                    slika.postaviSirinu(200);
                    
                }
                break;
            default:
                //labela.setText("prekid");
        }
    }//GEN-LAST:event_jbutSLIKEActionPerformed

    private void butonsnimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonsnimiActionPerformed
        Auto a=new Auto();
        a.setBoja(textboja.getText());
        a.setCijenaVozila(textcijena.getText());
        a.setDodatnaOprema(textAdodatnaop.getText());
        a.setGodinaProizvodnje(textgodinaproizvodnje.getText());
        a.setMarkaVozila(textmarka.getText());
        a.setPrijedjeniKilometri(textpredjkilom.getText());
        a.setSnagaUKilovatima(textsnagakW.getText());
        a.setStatus(textstatus.getText());
        a.setTipVozila(texttip.getText());
        a.setVrstaGoriva(textvrstagoriva.getText());
        a.setVrstaMotora(textvrstamotora.getText());
        a.setVrstaVozila(textvrsta.getText());
        a.setZapreminaMotora(textzapreminaccm.getText());
        
        String sl="";
        for(int i=0;i<f.getAbsolutePath().length();i++){
            if(f.getAbsolutePath().charAt(i)=='\\'){
                    sl=sl+"\\";
            }
            sl=sl+f.getAbsolutePath().charAt(i);
         a.setSlika(sl);   
        }
        
        
       
        
        
        
        JOptionPane opt=new JOptionPane();
        
        if(a.valjaniPodaci()){
            boolean uspjesno=Metode.spremiAuto(a);
            
            if(uspjesno){
                
                opt.showMessageDialog(this,"Uspje�no snimljeno","OBAVIJEST",JOptionPane.INFORMATION_MESSAGE);
                reset();
                v=Metode.dajSveAute();
            }else{
                opt.showMessageDialog(this,"Nije snimljeno","POZOR",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            opt.showMessageDialog(this,"Molim upi�ite marku i tip auta","POZOR",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_butonsnimiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jpanunosautomobilaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpanunosautomobilaComponentHidden
        
    }//GEN-LAST:event_jpanunosautomobilaComponentHidden

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden
    public void reset(){
       textAdodatnaop.setText("");
       textboja.setText("");
       textcijena.setText("");
       textgodinaproizvodnje.setText("");
       textmarka.setText("");
       textpredjkilom.setText("");
       textsnagakW.setText("");
       textstatus.setText("");
       texttip.setText("");
       textvrsta.setText("");
       textvrstagoriva.setText("");
       textvrstamotora.setText("");
       textzapreminaccm.setText("");
       slika2.obrisiSliku();
   }
     private void prikaziAuto() {
          System.out.println("trenutnaPozicija="+trenutnaPozicija);
          if (v.size() > 0) {
              
          Auto a=v.elementAt(trenutnaPozicija);
          
          System.out.println("a="+a);
          System.out.println(""+a.getId());
          
          patadodatnaoprema.setText(a.getDodatnaOprema());
          patxtboja.setText(a.getBoja());
          patxtcijena.setText(a.getCijenaVozila());
          patxtgodinapr.setText(a.getGodinaProizvodnje());
          patxtmarka.setText(a.getMarkaVozila());
          patxtprijedkil.setText(a.getPrijedjeniKilometri());
          patxtsnaga.setText(a.getSnagaUKilovatima());
          patxtstatus.setText(a.getStatus());
          patxttip.setText(a.getTipVozila());
          patxtvrsta.setText(a.getVrstaVozila());
          patxtvrstagoriva.setText(a.getVrstaGoriva());
          patxtvrstamotora.setText(a.getVrstaMotora());
          patxtzapremina.setText(a.getZapreminaMotora());
          slika2.prikaziSliku(a.getSlika());
          }
     }
     
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radnosucelje().setVisible(true);
            }
        });
        
       
      
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonsnimi;
    private javax.swing.JComboBox cmbkriterij;
    private javax.swing.JButton dugmePretrazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbutSLIKE;
    private javax.swing.JButton jbutlistajnapred;
    private javax.swing.JButton jbutlistajnazad;
    private javax.swing.JPanel jpanponudaautomobila;
    private javax.swing.JPanel jpanpretrazivac;
    private javax.swing.JPanel jpanunosautomobila;
    private javax.swing.JTextArea patadodatnaoprema;
    private javax.swing.JTextField patxtboja;
    private javax.swing.JTextField patxtcijena;
    private javax.swing.JTextField patxtgodinapr;
    private javax.swing.JTextField patxtmarka;
    private javax.swing.JTextField patxtprijedkil;
    private javax.swing.JTextField patxtsnaga;
    private javax.swing.JTextField patxtstatus;
    private javax.swing.JTextField patxttip;
    private javax.swing.JTextField patxtvrsta;
    private javax.swing.JTextField patxtvrstagoriva;
    private javax.swing.JTextField patxtvrstamotora;
    private javax.swing.JTextField patxtzapremina;
    private javax.swing.JTable tablicapretrazivaca;
    private javax.swing.JTextArea textAdodatnaop;
    private javax.swing.JTextField textboja;
    private javax.swing.JTextField textcijena;
    private javax.swing.JTextField textgodinaproizvodnje;
    private javax.swing.JTextField textmarka;
    private javax.swing.JTextField textpredjkilom;
    private javax.swing.JTextField textsnagakW;
    private javax.swing.JTextField textstatus;
    private javax.swing.JTextField texttip;
    private javax.swing.JTextField textvrsta;
    private javax.swing.JTextField textvrstagoriva;
    private javax.swing.JTextField textvrstamotora;
    private javax.swing.JTextField textzapreminaccm;
    private javax.swing.JTextField txtupit;
    // End of variables declaration//GEN-END:variables
    
}
